### ISSUE TITLE
우리메일 클래스 수정

### ISSUE THREAD

**Issue by ForPeople** [kijin/xe-xternal-mailer#1]
우리메일 내부 인증서 이슈때문에 클래스 코드를 일부 수정합니다.

		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);
		curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, true);

수정 후

		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
		curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);

인증서가 startssl 무료버전 보다 후진 코모도 positive ssl 로 바뀌었습니다. ㅡ.ㅡ;

**Comment by kijin** [comment]
일단 고쳐놓긴 했습니다만, 혹시 우리메일 서버의 SSL 설정이 잘못된 것 아닌가요?

[제 홈페이지](https://www.kijinsung.com/)도 님과 같은 PositiveSSL 인증서를 사용하지만 curl 요청시 문제가 발생하지 않습니다. 그 밖에도 최근에 PositiveSSL을 적용한 사이트가 몇 개 더 있는데 모두 문제 없고요.

요즘 PositiveSSL 인증서를 구입하면 중간 인증서(intermediate certificate)가 2개 더 따라옵니다.

- Comodo RSA Domain Validation Secure Server CA
- Comodo RSA Certification Authority

이렇게 2개 모두 설치하셨는지요? 아파치라면 `SSLCACertificateFile` 설정이 참조하는 파일에 인증서 2개를 위의 순서대로 연달아 붙여야 합니다.

중간 인증서가 모두 정상적으로 설치된 경우 아래의 명령으로 SSL 상태를 확인했을 때

    openssl s_client -connect woorimail.com:20080 -status

아래와 같이 나와야 합니다. (여기까지만 확인하고 `Ctrl+C` 눌러서 테스트 중단하세요.)

    Certificate chain
    0 s:/OU=Domain Control Validated/OU=PositiveSSL/CN=woorimail.com
      i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
    1 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
      i:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
    2 s:/C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Certification Authority
      i:/C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root

님의 서버는 현재 2번 인증서가 누락되어서 대부분의 리눅스 배포판이 신뢰하는 `AddTrust External CA Root` 인증서까지 신뢰의 고리가 이어지지 않고 있는 것 같습니다.

[여기](https://wiki.mozilla.org/Security/Server_Side_TLS)를 참조하셔서 OCSP stapling, dhparam까지 셋팅하시면 서버 부하도 줄어들고 더욱 좋습니다. (단, dhparam은 오래된 프로그램들과의 호환을 위해 1024비트로 해주세요.)

**Comment by ForPeople** [comment]
아.. 자세한 설명 감사합니다.

https://www.comodossl.co.kr/certificate/ssl-installation-guides/Apache-csr-crt.aspx
7. 인증서 설치

이곳의 설명이 좀 잘못된 것 같습니다.
구글링을 통해서 잘 설치해 봐야 겠습니다.

**Comment by ForPeople** [comment]
정상 설치된 것 같습니다.

			curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 1);
			curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 1);

통신이 잘 되는군요 ㅠㅠ

**Comment by kijin** [comment]
수고하셨습니다 ^^

아, 그리고 최근 버전의 `curl`에서는 `CURLOPT_SSL_VERIFYHOST` 설정을 2로 해야 하네요. 1로 하면 경고메시지가 나옵니다. (불리언 값을 넣는 게 아니었음... 헐...)

**Comment by ForPeople** [comment]
헐...
최근 버전 아닌 서버와 최근 버전 서버를 구분해서 2로 설정해주기는 힘드네요 ;;
그냥 0으로 해버릴까요...

**Comment by kijin** [comment]
예전 버전에서도 2를 써도 괜찮은 것으로 알고 있습니다만, 한번 테스트해 보세요.

**Comment by ForPeople** [comment]
http://curl.haxx.se/libcurl/c/CURLOPT_SSL_VERIFYHOST.html

사실상 디폴트가 2이고 SSL 에서 정식 인증을 하려면 1 말고 2를 해야 하는게 맞나 보네요...

테스트 해보니 2로 해도 잘 됩니다.
